export const projects = [
  {
    id: "restaurant-le-gourmet",
    title: "Restaurant Le Gourmet",
    category: "Site Vitrine",
    description: "Site élégant pour un restaurant gastronomique avec système de réservation en ligne.",
    fullDescription:
      "Création d'un site web élégant et moderne pour le restaurant gastronomique Le Gourmet. Le projet incluait la conception d'une interface utilisateur raffinée, l'intégration d'un système de réservation en ligne, une galerie photo des plats, et l'optimisation SEO pour améliorer la visibilité locale.",
    image: "/elegant-restaurant-website-mockup.png",
    images: [
      "/elegant-restaurant-website-mockup.png",
      "/restaurant-menu-page.png",
      "/restaurant-reservation-system.png",
    ],
    tags: ["Design", "Réservations", "SEO"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Stripe", "Google Maps API"],
    url: "https://restaurant-le-gourmet.fr",
    duration: "6 semaines",
    client: "Restaurant Le Gourmet",
    features: [
      "Design responsive et élégant",
      "Système de réservation en ligne",
      "Galerie photo des plats",
      "Menu interactif",
      "Intégration Google Maps",
      "Optimisation SEO locale",
    ],
  },
  {
    id: "sekoba-coiffure",
    title: "SEKOBA COIFFURE",
    category: "Site Vitrine",
    description: "Site vitrine moderne pour un salon de coiffure basé à Genève avec prise de rendez-vous en ligne.",
    fullDescription:
      "Création d’un site web vitrine élégant et moderne pour SEKOBA COIFFURE, un salon basé à Genève. Le projet incluait la présentation des services, une galerie photo, la prise de rendez-vous en ligne via Salonkee, et une optimisation SEO locale.",
    image: "/sekoba/cover.png",
    images: [
      "/sekoba/cover.png",
      "/sekoba/galerie1.png",
      "/sekoba/galerie2.png",
    ],
    tags: ["Design", "Réservations", "SEO"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
    url: "https://sekoba-coiffure.fr",
    duration: "5 semaines",
    client: "SEKOBA COIFFURE",
    features: [
      "Présentation des services du salon",
      "Galerie photo du salon",
      "Prise de rendez-vous en ligne via Salonkee",
      "Optimisation SEO locale",
    ],
  },
  {
    id: "boutique-mode-elegance",
    title: "Boutique Mode Élégance",
    category: "E-commerce",
    description: "Boutique en ligne complète avec catalogue produits et paiement sécurisé.",
    fullDescription:
      "Développement d'une boutique e-commerce complète pour Mode Élégance, spécialisée dans la mode féminine. Le projet comprenait la création d'un catalogue produits interactif, l'intégration de solutions de paiement sécurisées, un système de gestion des stocks, et une interface d'administration complète.",
    image: "/fashion-ecommerce-website-mockup.png",
    images: ["/fashion-ecommerce-website-mockup.png", "/fashion-product-catalog.png", "/fashion-checkout-process.png"],
    tags: ["E-commerce", "Paiement", "Mobile"],
    technologies: ["Next.js", "Stripe", "Supabase", "Tailwind CSS", "Vercel"],
    url: "https://boutique-mode-elegance.fr",
    duration: "8 semaines",
    client: "Mode Élégance",
    features: [
      "Catalogue produits avec filtres avancés",
      "Panier d'achat et wishlist",
      "Paiement sécurisé Stripe",
      "Gestion des stocks en temps réel",
      "Interface d'administration",
      "Design mobile-first",
    ],
  },
  {
    id: "cabinet-medical-sante",
    title: "Cabinet Médical Santé+",
    category: "Application Web",
    description: "Plateforme de gestion des rendez-vous et dossiers patients pour cabinet médical.",
    fullDescription:
      "Développement d'une application web sécurisée pour la gestion complète d'un cabinet médical. La plateforme permet la prise de rendez-vous en ligne, la gestion des dossiers patients, la téléconsultation, et respecte toutes les normes RGPD et de sécurité médicale.",
    image: "/medical-appointment-web-app-mockup.png",
    images: [
      "/medical-appointment-web-app-mockup.png",
      "/medical-patient-dashboard.png",
      "/medical-doctor-interface.png",
    ],
    tags: ["Gestion", "Sécurité", "RGPD"],
    technologies: ["Next.js", "Supabase", "TypeScript", "Tailwind CSS", "WebRTC"],
    url: "https://cabinet-sante-plus.fr",
    duration: "12 semaines",
    client: "Cabinet Médical Santé+",
    features: [
      "Prise de rendez-vous en ligne",
      "Gestion des dossiers patients",
      "Téléconsultation intégrée",
      "Conformité RGPD",
      "Chiffrement des données",
      "Interface médecin et patient",
    ],
  },
  {
    id: "agence-immobiliere-premium",
    title: "Agence Immobilière Premium",
    category: "Site Vitrine",
    description: "Site moderne avec recherche avancée et visite virtuelle des biens immobiliers.",
    fullDescription:
      "Création d'un site web moderne pour une agence immobilière haut de gamme. Le projet incluait un système de recherche avancée avec filtres géographiques, l'intégration de visites virtuelles 360°, un CRM pour la gestion des prospects, et une interface d'administration pour la gestion des biens.",
    image: "/real-estate-website-mockup.png",
    images: ["/real-estate-website-mockup.png", "/real-estate-search-filters.png", "/real-estate-virtual-tour.png"],
    tags: ["Recherche", "Géolocalisation", "CRM"],
    technologies: ["Next.js", "Google Maps API", "Supabase", "Tailwind CSS", "Three.js"],
    url: "https://agence-immobiliere-premium.fr",
    duration: "10 semaines",
    client: "Agence Immobilière Premium",
    features: [
      "Recherche avancée avec filtres",
      "Géolocalisation des biens",
      "Visites virtuelles 360°",
      "CRM intégré",
      "Estimation en ligne",
      "Interface agent immobilier",
    ],
  },
  {
    id: "startup-techinnovate",
    title: "Startup TechInnovate",
    category: "Landing Page",
    description: "Landing page optimisée pour la conversion avec A/B testing intégré.",
    fullDescription:
      "Développement d'une landing page haute performance pour la startup TechInnovate. Le projet se concentrait sur l'optimisation du taux de conversion avec des tests A/B intégrés, une analyse comportementale avancée, et une interface utilisateur conçue pour maximiser les inscriptions et les démonstrations produit.",
    image: "/tech-startup-landing-page-mockup.png",
    images: [
      "/tech-startup-landing-page-mockup.png",
      "/startup-conversion-funnel.png",
      "/startup-analytics-dashboard.png",
    ],
    tags: ["Conversion", "Analytics", "A/B Testing"],
    technologies: ["Next.js", "Vercel Analytics", "Tailwind CSS", "Framer Motion", "TypeScript"],
    url: "https://techinnovate-startup.com",
    duration: "4 semaines",
    client: "TechInnovate",
    features: [
      "Design optimisé pour la conversion",
      "A/B testing intégré",
      "Analytics avancées",
      "Animations fluides",
      "Formulaires optimisés",
      "Performance maximale",
    ],
  },
  {
    id: "ecole-formation-pro",
    title: "École de Formation Pro",
    category: "Plateforme E-learning",
    description: "Plateforme complète de formation en ligne avec suivi des progrès.",
    fullDescription:
      "Création d'une plateforme e-learning complète pour l'École de Formation Pro. Le projet comprenait un système de gestion des cours, un lecteur vidéo avancé, un suivi des progrès en temps réel, des quiz interactifs, et un système de certification automatisé.",
    image: "/elearning-platform-mockup.png",
    images: ["/elearning-platform-mockup.png", "/elearning-course-player.png", "/elearning-progress-tracking.png"],
    tags: ["Formation", "Vidéo", "Certification"],
    technologies: ["Next.js", "Supabase", "Video.js", "Tailwind CSS", "PDF-lib"],
    url: "https://ecole-formation-pro.fr",
    duration: "14 semaines",
    client: "École de Formation Pro",
    features: [
      "Lecteur vidéo avancé",
      "Suivi des progrès",
      "Quiz interactifs",
      "Certification automatisée",
      "Forum communautaire",
      "Interface formateur/étudiant",
    ],
  },
]

export function getProjectById(id: string) {
  return projects.find((project) => project.id === id)
}

export function getAllProjects() {
  return projects
}
